#!/bin/bash

echo '{'
echo '  "statVersion": "1.0.0",'
echo '  "process": {'
echo '    "name": "One two three example process",'
echo '    "version": "1"'
echo '  },'
echo '  "findings": ['
sleep 1
echo '    {'
echo '      "failure": false,'
echo '      "rule": "Go to your room",'
echo '      "description": "I told you zero times"'
echo '    },'
sleep 1
echo '    {'
echo '      "failure": false,'
echo '      "rule": "Go to your room",'
echo '      "description": "I told you once",'
echo '      "location": {'
echo '          "path": "/some/path.txt",'
echo '          "beginLine": 1,'
echo '          "endLine": 2'
echo '      }'
echo '    },'
sleep 2
echo '    {'
echo '      "failure": false,'
echo '      "rule": "Go to your room",'
echo '      "description": "I told you twice",'
echo '      "location": {'
echo '          "path": "/some/path.txt",'
echo '          "beginLine": 1,'
echo '          "endLine": 2,'
echo '          "beginColumn": 23,'
echo '          "endColumn": 29'
echo '      }'
echo '    },'
sleep 3
echo '    {'
echo '      "failure": true,'
echo '      "rule": "Go to your room",'
echo '      "description": "I told you three times",'
echo '      "recommendation": "Reword to avoid the passive voice.",'
echo '      "location": {'
echo '          "path": "/some/path.txt",'
echo '          "beginLine": 1,'
echo '          "endLine": 1,'
echo '          "beginColumn": 23,'
echo '          "endColumn": 29'
echo '      }'
echo '    }'
sleep 1
echo '  ]'
echo '}'